from turtle import *
def sun():
    pensize(2)
    speed(10)
    begin_fill()
    color('yellow')
    for i in range(18):
        forward(50)
        left(100)
    end_fill()
def zemlya():
    for i in range(2):
        color('green')
        begin_fill()
        forward(250)
        right(90)
        forward(300)
        right(90)
        forward(300)
        end_fill()
def nebo():
    for i in range(2):
        color('light blue')
        begin_fill()
        forward(250)
        left(90)
        forward(300)
        left(90)
        forward(300)
        end_fill()
def dom():
    begin_fill()
    for i in range(2):
        color('orange')
        forward(30)
        left(90)
        forward(30)
        left(90)
    end_fill()
    forward(30)
    left(90)
    forward(30)
    right(90)
    begin_fill()
    color('brown')
    forward(5)
    left(120)
    forward(40)
    left(120)
    forward(40)
    left(110)
    forward(5)

    end_fill()
def drefo():
    begin_fill()
    color('lime')
    circle(20)
    end_fill()
    begin_fill()
    color('brown')
    right(90)
    for i in range(2):
        forward(30)


    end_fill()
def polana():
    color('lime')
    left(90)
    forward(5)
    penup()
    left(90)
    forward(7)
    left(90)
    forward(2)
    pendown()
    forward(5)
    penup()
    right(90)
    forward(7)
    left(90)
    forward(2)
    pendown()
    forward(5)
    penup()
    left(90)
    forward(7)
    left(90)
    forward(2)
    pendown()
    forward(5)
    penup()
    left(90)
    forward(7)
    right(90)
    forward(2)
    pendown()
    forward(5) 
    penup()
    left(90)
    forward(7)
    right(90)
    forward(2)
    pendown()
    forward(5)  
    penup()
    left(90)
    forward(7)
    left(90)
    forward(2)
    pendown()
    forward(5)
    penup()
    left(90)
    forward(7)
    right(90)
    forward(2)
    pendown()
    forward(5)
    penup()
    left(90)
    forward(7)
    left(90)
    forward(2)
    pendown()
    forward(5)
def okna():
    for i in range(2):
        begin_fill()
        color('yellow')
        forward(5)
        left(90)
        forward(10)
        left(90)
        end_fill()
